#!/usr/bin/env python3
"""Interactive setup for Signal History persistence.

This script helps configure persistence for Signal History so it survives
code updates, Render free-tier restarts, and redeploys.

Two methods:
1. GitHub Gist sync (recommended for Render free tier)
2. External data directory (recommended for local development)
3. Both (maximum safety)

Usage:
    python scripts/setup_persistence.py
"""

import os
import sys
from pathlib import Path


def main():
    print("=" * 60)
    print("📦 TradingAgents Signal History Persistence Setup")
    print("=" * 60)
    
    # Check current status
    env_file = Path(".env")
    has_token = bool(os.environ.get("GITHUB_TOKEN"))
    has_pulse_gist = bool(os.environ.get("PULSE_GIST_ID"))
    has_history_gist = bool(os.environ.get("HISTORY_GIST_ID"))
    external_dir = os.environ.get("EVAL_RESULTS_DIR")
    
    print("\n📊 Current Status:")
    print(f"  GitHub Token: {'✓ Set' if has_token else '✗ Not set'}")
    print(f"  Pulse Gist: {'✓ Set' if has_pulse_gist else '✗ Not set'}")
    print(f"  History Gist: {'✓ Set' if has_history_gist else '✗ Not set'}")
    print(f"  External Dir: {external_dir if external_dir else '✗ Not set'}")
    
    if has_token and has_pulse_gist and has_history_gist:
        print("\n✅ GitHub Gist persistence is already configured!")
        response = input("\nDo you want to also set up external directory? (y/n): ").strip().lower()
        if response != 'y':
            print("\nYou're all set! Restart your server to apply any changes.")
            return
    
    print("\n🔧 Choose persistence method:")
    print("1. GitHub Gist (recommended for Render free tier)")
    print("   - Free, zero infrastructure, survives filesystem wipes")
    print("   - Limited to 100 most recent analyses per ticker")
    print()
    print("2. External directory (recommended for local development)")
    print("   - Fast local access, unlimited storage")
    print("   - Data survives git operations")
    print()
    print("3. Both (maximum safety)")
    print("   - External directory for fast access")
    print("   - GitHub Gist as backup for cloud deployments")
    print()
    
    choice = input("Choice (1/2/3): ").strip()
    
    if choice == "1":
        setup_gist_only(env_file)
    elif choice == "2":
        setup_external_only(env_file)
    elif choice == "3":
        setup_both(env_file)
    else:
        print("\n❌ Invalid choice. Exiting.")
        sys.exit(1)
    
    print("\n" + "=" * 60)
    print("✅ Setup complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Review the .env file that was created")
    print("2. Restart your server: python server.py")
    print("3. Check the logs for persistence status on startup")
    print("\nIf using GitHub Gist, your data will now sync automatically.")
    print("If using external directory, data is stored outside the repo.")


def setup_gist_only(env_file: Path):
    """Configure GitHub Gist sync only."""
    print("\n" + "-" * 60)
    print("🔗 GitHub Gist Setup")
    print("-" * 60)
    print("\nStep 1: Create a GitHub Personal Access Token")
    print("  1. Go to: https://github.com/settings/tokens")
    print("  2. Click 'Generate new token (classic)'")
    print("  3. Select scope: 'gist' (create and edit gists)")
    print("  4. Generate and copy the token")
    print()
    print("Step 2: Create two empty gists at https://gist.github.com")
    print("  - One for pulse data (can be empty)")
    print("  - One for history data (can be empty)")
    print("  Copy the gist IDs from the URLs")
    print("  Example: https://gist.github.com/username/XXXXXXXXXX")
    print("                              ^^^^^^^^^^ gist ID")
    
    token = input("\nGitHub Token: ").strip()
    pulse_gist = input("Pulse Gist ID: ").strip()
    history_gist = input("History Gist ID: ").strip()
    
    if not token or not pulse_gist or not history_gist:
        print("\n❌ All fields are required. Exiting.")
        sys.exit(1)
    
    # Write to .env
    env_content = f"""# TradingAgents Persistence Configuration
# Generated by setup_persistence.py

# GitHub Gist Sync (for Render free tier persistence)
GITHUB_TOKEN={token}
PULSE_GIST_ID={pulse_gist}
HISTORY_GIST_ID={history_gist}
"""
    
    # Append or create
    if env_file.exists():
        with open(env_file, "a") as f:
            f.write("\n" + env_content)
    else:
        env_file.write_text(env_content)
    
    print(f"\n✅ Configuration saved to {env_file}")


def setup_external_only(env_file: Path):
    """Configure external directory only."""
    print("\n" + "-" * 60)
    print("📁 External Directory Setup")
    print("-" * 60)
    
    default_dir = Path.home() / "TradingAgentsData"
    print(f"\nDefault directory: {default_dir}")
    custom = input(f"Enter directory path (or press Enter for default): ").strip()
    
    data_dir = Path(custom) if custom else default_dir
    eval_dir = data_dir / "eval_results"
    
    # Create directories
    try:
        eval_dir.mkdir(parents=True, exist_ok=True)
        (eval_dir / "pulse").mkdir(exist_ok=True)
        (eval_dir / "shadow").mkdir(exist_ok=True)
        print(f"\n✅ Created directory: {eval_dir}")
    except Exception as e:
        print(f"\n❌ Failed to create directory: {e}")
        sys.exit(1)
    
    # Write to .env
    env_content = f"""# TradingAgents Persistence Configuration
# Generated by setup_persistence.py

# External data directory (outside git repo)
EVAL_RESULTS_DIR={eval_dir}
PULSE_DIR={eval_dir / "pulse"}
SHADOW_DIR={eval_dir / "shadow"}
"""
    
    if env_file.exists():
        with open(env_file, "a") as f:
            f.write("\n" + env_content)
    else:
        env_file.write_text(env_content)
    
    print(f"✅ Configuration saved to {env_file}")


def setup_both(env_file: Path):
    """Configure both GitHub Gist and external directory."""
    print("\n" + "-" * 60)
    print("🛡️  Both Methods (Maximum Safety)")
    print("-" * 60)
    
    # External directory first
    default_dir = Path.home() / "TradingAgentsData"
    custom = input(f"External directory [{default_dir}]: ").strip()
    data_dir = Path(custom) if custom else default_dir
    eval_dir = data_dir / "eval_results"
    
    try:
        eval_dir.mkdir(parents=True, exist_ok=True)
        (eval_dir / "pulse").mkdir(exist_ok=True)
        (eval_dir / "shadow").mkdir(exist_ok=True)
        print(f"✅ Created directory: {eval_dir}")
    except Exception as e:
        print(f"❌ Failed to create directory: {e}")
        sys.exit(1)
    
    # GitHub Gist
    print("\nNow configure GitHub Gist (for cloud backup)...")
    print("  1. Create token at: https://github.com/settings/tokens")
    print("  2. Create two gists at: https://gist.github.com")
    print("     (scope: gist, can be empty)")
    
    token = input("\nGitHub Token: ").strip()
    pulse_gist = input("Pulse Gist ID: ").strip()
    history_gist = input("History Gist ID: ").strip()
    
    if not token or not pulse_gist or not history_gist:
        print("❌ All GitHub fields are required for 'both' option. Exiting.")
        sys.exit(1)
    
    # Write combined .env
    env_content = f"""# TradingAgents Persistence Configuration
# Generated by setup_persistence.py

# External data directory (for fast local access)
EVAL_RESULTS_DIR={eval_dir}
PULSE_DIR={eval_dir / "pulse"}
SHADOW_DIR={eval_dir / "shadow"}

# GitHub Gist Sync (for cloud backup)
GITHUB_TOKEN={token}
PULSE_GIST_ID={pulse_gist}
HISTORY_GIST_ID={history_gist}
"""
    
    if env_file.exists():
        # Backup existing
        backup = Path(".env.backup")
        backup.write_text(env_file.read_text())
        print(f"✅ Backed up existing .env to {backup}")
        
        with open(env_file, "a") as f:
            f.write("\n" + env_content)
    else:
        env_file.write_text(env_content)
    
    print(f"✅ Configuration saved to {env_file}")


if __name__ == "__main__":
    main()
